[package]
authors = ["Ivan Zorin <creator@localzet.com>"]
name = "localzet-jose"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "AGPL-3.0-or-later"
description = "Educational/reference JOSE implementation: JWS, JWE, JWK and JWT"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
thiserror = "2"
base64ct = { version = "1", features = ["alloc"] }

hmac = "0.12"
sha1 = "0.10"
sha2 = { version = "0.10", features = ["oid"] }
signature = "2"

rand = "0.8"
rsa = { version = "0.9", features = ["sha2", "pem"] }

p256 = { version = "0.13", features = ["ecdsa", "pkcs8", "pem"] }
p384 = { version = "0.13", features = ["ecdsa", "pkcs8", "pem"] }
p521 = { version = "0.13", features = ["ecdsa", "pkcs8", "pem"] }
k256 = { version = "0.13", features = ["ecdsa", "pkcs8", "pem"] }

ed25519-dalek = { version = "2", features = ["pkcs8", "pem", "rand_core"] }

aes-gcm = "0.10"

[dev-dependencies]
hex = "0.4"
